mqtt:
  # TLS parameters.
  tls:
    ca_certs: /home/ali/onboard/device_certificates/rootCA.crt
    certfile: /home/ali/onboard/device_certificates/certificate.pem.crt
    keyfile: /home/ali/onboard/device_certificates/private.pem.key

  # Connection parameters.
  connection:
    host: ahmj34rbzc71v-ats.iot.eu-central-1.amazonaws.com
    port: 8883
    keepalive: 60

  # MQTT parameters.
  client:
    client_id: QA_017671715646
    protocol: 3
bridge:
  # Bridge from ROS to MQTT.
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: vda5050_msgs.msg:State
    topic_from: /state
    topic_to: qa/QA_017671715646/state

  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: vda5050_msgs.msg:Visualization
    topic_from: /visualization
    topic_to: qa/QA_017671715646/visualization

  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: vda5050_msgs.msg:Connection
    topic_from: /connection
    topic_to: qa/QA_017671715646/connection

  # Bridge from MQTT to ROS.
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: vda5050_msgs.msg:Action
    topic_from: qa/QA_017671715646/instantAction
    topic_to: /instantActions

  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: vda5050_msgs.msg:Order
    topic_from: qa/QA_017671715646/order
    topic_to: /order_from_mc

  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: vda5050_msgs.msg:ZoneUpdate
    topic_from: qa/QA_017671715646/zones
    topic_to: /zones
